option set technology HAPS-70
option set use_fsm_explorer 0
option set maxfan 10000
option set disable_io_insertion 0
option set retiming 0
option set no_sequential_opt 0
option set pipe 1 
option set resource_sharing 1
option set fix_gated_and_generated_clocks 1
option set enable_prepacking 1
option set verification_mode 0
option set write_verilog 1
option set design_flow synthesis
option set write_verilog 1
option set continue_on_error 1
option set symbolic_fsm_compiler 0
option set multi_file_compilation_unit 1
option set dc_root /p/com/eda/synopsys/designcompiler/D-2010.03-SP5-2/
option set dw_foundation 1
option set auto_infer_blackbox 0
