// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_top module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// core_inst
//   -> s1n_7
//     -> sm1_8
//       -> instr
//     -> sm1_9
//       -> data
//     -> sm1_10
//       -> peri_device
// core_data
//   -> s1n_11
//     -> sm1_8
//       -> instr
//     -> sm1_9
//       -> data
//     -> sm1_10
//       -> peri_device
// spi
//   -> s1n_12
//     -> sm1_8
//       -> instr
//     -> sm1_9
//       -> data
//     -> sm1_10
//       -> peri_device
// jtag
//   -> s1n_13
//     -> sm1_8
//       -> instr
//     -> sm1_9
//       -> data
//     -> sm1_10
//       -> peri_device

module xbar_top (
  input clk_i,
  input rst_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_core_inst_i,
  output tlul_pkg::tl_d2h_t tl_core_inst_o,
  input  tlul_pkg::tl_h2d_t tl_core_data_i,
  output tlul_pkg::tl_d2h_t tl_core_data_o,
  input  tlul_pkg::tl_h2d_t tl_spi_i,
  output tlul_pkg::tl_d2h_t tl_spi_o,
  input  tlul_pkg::tl_h2d_t tl_jtag_i,
  output tlul_pkg::tl_d2h_t tl_jtag_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_instr_o,
  input  tlul_pkg::tl_d2h_t tl_instr_i,
  output tlul_pkg::tl_h2d_t tl_data_o,
  input  tlul_pkg::tl_d2h_t tl_data_i,
  output tlul_pkg::tl_h2d_t tl_peri_device_o,
  input  tlul_pkg::tl_d2h_t tl_peri_device_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_top_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_s1n_7_us_h2d ;
  tl_d2h_t tl_s1n_7_us_d2h ;


  tl_h2d_t tl_s1n_7_ds_h2d [3];
  tl_d2h_t tl_s1n_7_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_7;


  tl_h2d_t tl_sm1_8_us_h2d [4];
  tl_d2h_t tl_sm1_8_us_d2h [4];

  tl_h2d_t tl_sm1_8_ds_h2d ;
  tl_d2h_t tl_sm1_8_ds_d2h ;


  tl_h2d_t tl_sm1_9_us_h2d [4];
  tl_d2h_t tl_sm1_9_us_d2h [4];

  tl_h2d_t tl_sm1_9_ds_h2d ;
  tl_d2h_t tl_sm1_9_ds_d2h ;


  tl_h2d_t tl_sm1_10_us_h2d [4];
  tl_d2h_t tl_sm1_10_us_d2h [4];

  tl_h2d_t tl_sm1_10_ds_h2d ;
  tl_d2h_t tl_sm1_10_ds_d2h ;

  tl_h2d_t tl_s1n_11_us_h2d ;
  tl_d2h_t tl_s1n_11_us_d2h ;


  tl_h2d_t tl_s1n_11_ds_h2d [3];
  tl_d2h_t tl_s1n_11_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_11;

  tl_h2d_t tl_s1n_12_us_h2d ;
  tl_d2h_t tl_s1n_12_us_d2h ;


  tl_h2d_t tl_s1n_12_ds_h2d [3];
  tl_d2h_t tl_s1n_12_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_12;

  tl_h2d_t tl_s1n_13_us_h2d ;
  tl_d2h_t tl_s1n_13_us_d2h ;


  tl_h2d_t tl_s1n_13_ds_h2d [3];
  tl_d2h_t tl_s1n_13_ds_d2h [3];

  // Create steering signal
  logic [1:0] dev_sel_s1n_13;



  assign tl_sm1_8_us_h2d[0] = tl_s1n_7_ds_h2d[0];
  assign tl_s1n_7_ds_d2h[0] = tl_sm1_8_us_d2h[0];

  assign tl_sm1_9_us_h2d[0] = tl_s1n_7_ds_h2d[1];
  assign tl_s1n_7_ds_d2h[1] = tl_sm1_9_us_d2h[0];

  assign tl_sm1_10_us_h2d[0] = tl_s1n_7_ds_h2d[2];
  assign tl_s1n_7_ds_d2h[2] = tl_sm1_10_us_d2h[0];

  assign tl_sm1_8_us_h2d[1] = tl_s1n_11_ds_h2d[0];
  assign tl_s1n_11_ds_d2h[0] = tl_sm1_8_us_d2h[1];

  assign tl_sm1_9_us_h2d[1] = tl_s1n_11_ds_h2d[1];
  assign tl_s1n_11_ds_d2h[1] = tl_sm1_9_us_d2h[1];

  assign tl_sm1_10_us_h2d[1] = tl_s1n_11_ds_h2d[2];
  assign tl_s1n_11_ds_d2h[2] = tl_sm1_10_us_d2h[1];

  assign tl_sm1_8_us_h2d[2] = tl_s1n_12_ds_h2d[0];
  assign tl_s1n_12_ds_d2h[0] = tl_sm1_8_us_d2h[2];

  assign tl_sm1_9_us_h2d[2] = tl_s1n_12_ds_h2d[1];
  assign tl_s1n_12_ds_d2h[1] = tl_sm1_9_us_d2h[2];

  assign tl_sm1_10_us_h2d[2] = tl_s1n_12_ds_h2d[2];
  assign tl_s1n_12_ds_d2h[2] = tl_sm1_10_us_d2h[2];

  assign tl_sm1_8_us_h2d[3] = tl_s1n_13_ds_h2d[0];
  assign tl_s1n_13_ds_d2h[0] = tl_sm1_8_us_d2h[3];

  assign tl_sm1_9_us_h2d[3] = tl_s1n_13_ds_h2d[1];
  assign tl_s1n_13_ds_d2h[1] = tl_sm1_9_us_d2h[3];

  assign tl_sm1_10_us_h2d[3] = tl_s1n_13_ds_h2d[2];
  assign tl_s1n_13_ds_d2h[2] = tl_sm1_10_us_d2h[3];

  assign tl_s1n_7_us_h2d = tl_core_inst_i;
  assign tl_core_inst_o = tl_s1n_7_us_d2h;

  assign tl_instr_o = tl_sm1_8_ds_h2d;
  assign tl_sm1_8_ds_d2h = tl_instr_i;

  assign tl_data_o = tl_sm1_9_ds_h2d;
  assign tl_sm1_9_ds_d2h = tl_data_i;

  assign tl_peri_device_o = tl_sm1_10_ds_h2d;
  assign tl_sm1_10_ds_d2h = tl_peri_device_i;

  assign tl_s1n_11_us_h2d = tl_core_data_i;
  assign tl_core_data_o = tl_s1n_11_us_d2h;

  assign tl_s1n_12_us_h2d = tl_spi_i;
  assign tl_spi_o = tl_s1n_12_us_d2h;

  assign tl_s1n_13_us_h2d = tl_jtag_i;
  assign tl_jtag_o = tl_s1n_13_us_d2h;

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_7 = 2'd3;
    if ((tl_s1n_7_us_h2d.a_address &
         ~(ADDR_MASK_INSTR)) == ADDR_SPACE_INSTR) begin
      dev_sel_s1n_7 = 2'd0;

    end else if ((tl_s1n_7_us_h2d.a_address &
                  ~(ADDR_MASK_DATA)) == ADDR_SPACE_DATA) begin
      dev_sel_s1n_7 = 2'd1;

    end else if ((tl_s1n_7_us_h2d.a_address &
                  ~(ADDR_MASK_PERI_DEVICE)) == ADDR_SPACE_PERI_DEVICE) begin
      dev_sel_s1n_7 = 2'd2;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_11 = 2'd3;
    if ((tl_s1n_11_us_h2d.a_address &
         ~(ADDR_MASK_INSTR)) == ADDR_SPACE_INSTR) begin
      dev_sel_s1n_11 = 2'd0;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_DATA)) == ADDR_SPACE_DATA) begin
      dev_sel_s1n_11 = 2'd1;

    end else if ((tl_s1n_11_us_h2d.a_address &
                  ~(ADDR_MASK_PERI_DEVICE)) == ADDR_SPACE_PERI_DEVICE) begin
      dev_sel_s1n_11 = 2'd2;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_12 = 2'd3;
    if ((tl_s1n_12_us_h2d.a_address &
         ~(ADDR_MASK_INSTR)) == ADDR_SPACE_INSTR) begin
      dev_sel_s1n_12 = 2'd0;

    end else if ((tl_s1n_12_us_h2d.a_address &
                  ~(ADDR_MASK_DATA)) == ADDR_SPACE_DATA) begin
      dev_sel_s1n_12 = 2'd1;

    end else if ((tl_s1n_12_us_h2d.a_address &
                  ~(ADDR_MASK_PERI_DEVICE)) == ADDR_SPACE_PERI_DEVICE) begin
      dev_sel_s1n_12 = 2'd2;
end
  end

  always_comb begin
    // default steering to generate error response if address is not within the range
    dev_sel_s1n_13 = 2'd3;
    if ((tl_s1n_13_us_h2d.a_address &
         ~(ADDR_MASK_INSTR)) == ADDR_SPACE_INSTR) begin
      dev_sel_s1n_13 = 2'd0;

    end else if ((tl_s1n_13_us_h2d.a_address &
                  ~(ADDR_MASK_DATA)) == ADDR_SPACE_DATA) begin
      dev_sel_s1n_13 = 2'd1;

    end else if ((tl_s1n_13_us_h2d.a_address &
                  ~(ADDR_MASK_PERI_DEVICE)) == ADDR_SPACE_PERI_DEVICE) begin
      dev_sel_s1n_13 = 2'd2;
end
  end


  // Instantiation phase
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_7 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_7_us_h2d),
    .tl_h_o       (tl_s1n_7_us_d2h),
    .tl_d_o       (tl_s1n_7_ds_h2d),
    .tl_d_i       (tl_s1n_7_ds_d2h),
    .dev_select_i (dev_sel_s1n_7)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_8 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_8_us_h2d),
    .tl_h_o       (tl_sm1_8_us_d2h),
    .tl_d_o       (tl_sm1_8_ds_h2d),
    .tl_d_i       (tl_sm1_8_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_9 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_9_us_h2d),
    .tl_h_o       (tl_sm1_9_us_d2h),
    .tl_d_o       (tl_sm1_9_ds_h2d),
    .tl_d_i       (tl_sm1_9_ds_d2h)
  );
  tlul_socket_m1 #(
    .HReqDepth (16'h0),
    .HRspDepth (16'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (4)
  ) u_sm1_10 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_10_us_h2d),
    .tl_h_o       (tl_sm1_10_us_d2h),
    .tl_d_o       (tl_sm1_10_ds_h2d),
    .tl_d_i       (tl_sm1_10_ds_d2h)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_11 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_11_us_h2d),
    .tl_h_o       (tl_s1n_11_us_d2h),
    .tl_d_o       (tl_s1n_11_ds_h2d),
    .tl_d_i       (tl_s1n_11_ds_d2h),
    .dev_select_i (dev_sel_s1n_11)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_12 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_12_us_h2d),
    .tl_h_o       (tl_s1n_12_us_d2h),
    .tl_d_o       (tl_s1n_12_ds_h2d),
    .tl_d_i       (tl_s1n_12_ds_d2h),
    .dev_select_i (dev_sel_s1n_12)
  );
  tlul_socket_1n #(
    .HReqDepth (4'h0),
    .HRspDepth (4'h0),
    .DReqDepth (12'h0),
    .DRspDepth (12'h0),
    .N         (3)
  ) u_s1n_13 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_s1n_13_us_h2d),
    .tl_h_o       (tl_s1n_13_us_d2h),
    .tl_d_o       (tl_s1n_13_ds_h2d),
    .tl_d_i       (tl_s1n_13_ds_d2h),
    .dev_select_i (dev_sel_s1n_13)
  );

endmodule
