# -*-cperl-*-
## this file generated by ACE_UTILS from the perl template: /p/hdk/rtl/proj_tools/rtltools_flows/xhdk74/17.04.03/templates/cfg/dc/ip_final_cfg.pm.template

package mss_top_top_final_cfg;
use vars qw (@ISA @EXPORT_OK $dc_cfg);
@EXPORT_OK = qw($dc_cfg);

$dc_cfg = {
    ace_lib => 'mss_top_rtl_lib',
    project => 'SIP',
    -block_type => "unit",
    -owner => ["<owner_user_name>",],
    -opus_lib => 'msstoptop',
    -enable_sg_dft => 1,
    -enable_static_check => 1,
    -instance_name => ['mss_top_top_tb.mss_top_top'],
    -bbox_file => [
     ],
    -search => [
     ],
    -rm_ctech_files  => [],
    -add_ctech_files => [],
    -defines => [ "INTEL_SVA_OFF",
                  "INTEL_NO_PWR_PINS",
                ],
    -children => [
                  ## list of children, particularly HIPs
                  ## NOTE block_type 'sip' is currently not allowed to have any children
                  qw()
     ],
};

sub get_data {
    return $dc_cfg;
}

1;



    
