`ifndef SYNTHESIS

//
// This is an automatically generated file from 
// dc_shell Version S-2021.06-SP1 -- Jul 13, 2021
//

// For simulation only. Do not modify.

module top_earlgrey_svsim #(
  
              parameter bit GpioGpioAsyncOn = 1,
                parameter OtpCtrlMemInitFile = "",
    parameter logic [15:0] LcCtrlChipGen = 16'h0000,
  parameter logic [15:0] LcCtrlChipRev = 16'h0000,
  parameter logic [31:0] LcCtrlIdcodeValue = jtag_id_pkg::JTAG_IDCODE,
          parameter bit UsbdevStub = 0,
  parameter int UsbdevRcvrWakeTimeUs = 100,
      parameter bit SecRstmgrAonCheck = 1'b1,
  parameter int SecRstmgrAonMaxSyncDelay = 2,
            parameter pinmux_pkg::target_cfg_t PinmuxAonTargetCfg = pinmux_pkg::DefaultTargetCfg,
        parameter bit SramCtrlRetAonInstrExec = 0,
    parameter bit SecFlashCtrlScrambleEn = 1,
  parameter int FlashCtrlProgFifoDepth = 4,
  parameter int FlashCtrlRdFifoDepth = 16,
    parameter logic [31:0] RvDmIdcodeValue = jtag_id_pkg::JTAG_IDCODE,
      parameter bit SecAesMasking = 1,
  parameter aes_pkg::sbox_impl_e SecAesSBoxImpl = aes_pkg::SBoxImplDom,
  parameter int unsigned SecAesStartTriggerDelay = 0,
  parameter bit SecAesAllowForcingMasks = 1'b0,
  parameter bit SecAesSkipPRNGReseeding = 1'b0,
      parameter bit KmacEnMasking = 1,
  parameter bit KmacSwKeyMasked = 0,
  parameter int SecKmacCmdDelay = 0,
  parameter bit SecKmacIdleAcceptSwMsg = 0,
    parameter bit OtbnStub = 0,
  parameter otbn_pkg::regfile_e OtbnRegFile = otbn_pkg::RegFileFF,
  parameter bit SecOtbnMuteUrnd = 0,
  parameter bit SecOtbnSkipUrndReseedAtStart = 0,
    parameter bit KeymgrKmacEnMasking = 1,
    parameter aes_pkg::sbox_impl_e CsrngSBoxImpl = aes_pkg::SBoxImplCanright,
    parameter bit EntropySrcStub = 0,
        parameter bit SramCtrlMainInstrExec = 1,
    parameter RomCtrlBootRomInitFile = "",
  parameter bit SecRomCtrlDisableScrambling = 1'b0,
    parameter bit RvCoreIbexPMPEnable = 1,
  parameter int unsigned RvCoreIbexPMPGranularity = 0,
  parameter int unsigned RvCoreIbexPMPNumRegions = 16,
  parameter int unsigned RvCoreIbexMHPMCounterNum = 10,
  parameter int unsigned RvCoreIbexMHPMCounterWidth = 32,
  parameter bit RvCoreIbexRV32E = 0,
  parameter ibex_pkg::rv32m_e RvCoreIbexRV32M = ibex_pkg::RV32MSingleCycle,
  parameter ibex_pkg::rv32b_e RvCoreIbexRV32B = ibex_pkg::RV32BOTEarlGrey,
  parameter ibex_pkg::regfile_e RvCoreIbexRegFile = ibex_pkg::RegFileFF,
  parameter bit RvCoreIbexBranchTargetALU = 1,
  parameter bit RvCoreIbexWritebackStage = 1,
  parameter bit RvCoreIbexICache = 1,
  parameter bit RvCoreIbexICacheECC = 1,
  parameter bit RvCoreIbexICacheScramble = 1,
  parameter bit RvCoreIbexBranchPredictor = 0,
  parameter bit RvCoreIbexDbgTriggerEn = 1,
  parameter int RvCoreIbexDbgHwBreakNum = 4,
  parameter bit RvCoreIbexSecureIbex = 1,
  parameter int unsigned RvCoreIbexDmHaltAddr =
      tl_main_pkg::ADDR_SPACE_RV_DM__MEM + dm::HaltAddress[31:0],
  parameter int unsigned RvCoreIbexDmExceptionAddr =
      tl_main_pkg::ADDR_SPACE_RV_DM__MEM + dm::ExceptionAddress[31:0],
  parameter bit RvCoreIbexPipeLine = 0
) (
    input        [46:0] mio_in_i,
  output logic [46:0] mio_out_o,
  output logic [46:0] mio_oe_o,
    input        [15:0] dio_in_i,
  output logic [15:0] dio_out_o,
  output logic [15:0] dio_oe_o,

    output prim_pad_wrapper_pkg::pad_attr_t [pinmux_reg_pkg::NMioPads-1:0] mio_attr_o,
  output prim_pad_wrapper_pkg::pad_attr_t [pinmux_reg_pkg::NDioPads-1:0] dio_attr_o,


    output ast_pkg::adc_ast_req_t       adc_req_o,
  input  ast_pkg::adc_ast_rsp_t       adc_rsp_i,
  input  edn_pkg::edn_req_t       ast_edn_req_i,
  output edn_pkg::edn_rsp_t       ast_edn_rsp_o,
  output lc_ctrl_pkg::lc_tx_t       ast_lc_dft_en_o,
  input  ast_pkg::ast_obs_ctrl_t       obs_ctrl_i,
  input  prim_ram_1p_pkg::ram_1p_cfg_t       ram_1p_cfg_i,
  input  prim_ram_2p_pkg::ram_2p_cfg_t       ram_2p_cfg_i,
  input  prim_rom_pkg::rom_cfg_t       rom_cfg_i,
  output prim_mubi_pkg::mubi4_t       clk_main_jitter_en_o,
  output prim_mubi_pkg::mubi4_t       io_clk_byp_req_o,
  input  prim_mubi_pkg::mubi4_t       io_clk_byp_ack_i,
  output prim_mubi_pkg::mubi4_t       all_clk_byp_req_o,
  input  prim_mubi_pkg::mubi4_t       all_clk_byp_ack_i,
  output prim_mubi_pkg::mubi4_t       hi_speed_sel_o,
  input  prim_mubi_pkg::mubi4_t       div_step_down_req_i,
  input  prim_mubi_pkg::mubi4_t       calib_rdy_i,
  input  prim_mubi_pkg::mubi4_t       flash_bist_enable_i,
  input  logic       flash_power_down_h_i,
  input  logic       flash_power_ready_h_i,
  inout   [1:0] flash_test_mode_a_io,
  inout         flash_test_voltage_h_io,
  output logic [7:0] flash_obs_o,
  output entropy_src_pkg::entropy_src_rng_req_t       es_rng_req_o,
  input  entropy_src_pkg::entropy_src_rng_rsp_t       es_rng_rsp_i,
  output logic       es_rng_fips_o,
  output tlul_pkg::tl_h2d_t       ast_tl_req_o,
  input  tlul_pkg::tl_d2h_t       ast_tl_rsp_i,
  output pinmux_pkg::dft_strap_test_req_t       dft_strap_test_o,
  input  logic       dft_hold_tap_sel_i,
  output logic       usb_dp_pullup_en_o,
  output logic       usb_dn_pullup_en_o,
  output pwrmgr_pkg::pwr_ast_req_t       pwrmgr_ast_req_o,
  input  pwrmgr_pkg::pwr_ast_rsp_t       pwrmgr_ast_rsp_i,
  output otp_ctrl_pkg::otp_ast_req_t       otp_ctrl_otp_ast_pwr_seq_o,
  input  otp_ctrl_pkg::otp_ast_rsp_t       otp_ctrl_otp_ast_pwr_seq_h_i,
  inout         otp_ext_voltage_h_io,
  output logic [7:0] otp_obs_o,
  input  logic [1:0] por_n_i,
  input  logic [31:0] fpga_info_i,
  input  ast_pkg::ast_alert_req_t       sensor_ctrl_ast_alert_req_i,
  output ast_pkg::ast_alert_rsp_t       sensor_ctrl_ast_alert_rsp_o,
  input  ast_pkg::ast_status_t       sensor_ctrl_ast_status_i,
  input  logic [8:0] ast2pinmux_i,
  input  prim_mubi_pkg::mubi4_t       ast_init_done_i,
  output logic       sck_monitor_o,
  input  logic       usbdev_usb_rx_d_i,
  output logic       usbdev_usb_tx_d_o,
  output logic       usbdev_usb_tx_se0_o,
  output logic       usbdev_usb_tx_use_d_se0_o,
  output logic       usbdev_usb_rx_enable_o,
  output logic       usbdev_usb_ref_val_o,
  output logic       usbdev_usb_ref_pulse_o,


    input clk_main_i,
  input clk_io_i,
  input clk_usb_i,
  input clk_aon_i,

    output clkmgr_pkg::clkmgr_out_t clks_ast_o,
  output rstmgr_pkg::rstmgr_out_t rsts_ast_o,

  input                      scan_rst_ni,   input                      scan_en_i,
  input prim_mubi_pkg::mubi4_t scanmode_i   );

  

  top_earlgrey top_earlgrey( {>>{ mio_in_i }}, {>>{ mio_out_o }}, 
        {>>{ mio_oe_o }}, {>>{ dio_in_i }}, {>>{ dio_out_o }}, 
        {>>{ dio_oe_o }}, {>>{ mio_attr_o }}, {>>{ dio_attr_o }}, 
        {>>{ adc_req_o }}, {>>{ adc_rsp_i }}, {>>{ ast_edn_req_i }}, 
        {>>{ ast_edn_rsp_o }}, {>>{ ast_lc_dft_en_o }}, {>>{ obs_ctrl_i }}, 
        {>>{ ram_1p_cfg_i }}, {>>{ ram_2p_cfg_i }}, {>>{ rom_cfg_i }}, 
        {>>{ clk_main_jitter_en_o }}, {>>{ io_clk_byp_req_o }}, 
        {>>{ io_clk_byp_ack_i }}, {>>{ all_clk_byp_req_o }}, 
        {>>{ all_clk_byp_ack_i }}, {>>{ hi_speed_sel_o }}, 
        {>>{ div_step_down_req_i }}, {>>{ calib_rdy_i }}, 
        {>>{ flash_bist_enable_i }}, {>>{ flash_power_down_h_i }}, 
        {>>{ flash_power_ready_h_i }}, {>>{ flash_test_mode_a_io }}, 
        {>>{ flash_test_voltage_h_io }}, {>>{ flash_obs_o }}, 
        {>>{ es_rng_req_o }}, {>>{ es_rng_rsp_i }}, {>>{ es_rng_fips_o }}, 
        {>>{ ast_tl_req_o }}, {>>{ ast_tl_rsp_i }}, {>>{ dft_strap_test_o }}, 
        {>>{ dft_hold_tap_sel_i }}, {>>{ usb_dp_pullup_en_o }}, 
        {>>{ usb_dn_pullup_en_o }}, {>>{ pwrmgr_ast_req_o }}, 
        {>>{ pwrmgr_ast_rsp_i }}, {>>{ otp_ctrl_otp_ast_pwr_seq_o }}, 
        {>>{ otp_ctrl_otp_ast_pwr_seq_h_i }}, {>>{ otp_ext_voltage_h_io }}, 
        {>>{ otp_obs_o }}, {>>{ por_n_i }}, {>>{ fpga_info_i }}, 
        {>>{ sensor_ctrl_ast_alert_req_i }}, 
        {>>{ sensor_ctrl_ast_alert_rsp_o }}, {>>{ sensor_ctrl_ast_status_i }}, 
        {>>{ ast2pinmux_i }}, {>>{ ast_init_done_i }}, {>>{ sck_monitor_o }}, 
        {>>{ usbdev_usb_rx_d_i }}, {>>{ usbdev_usb_tx_d_o }}, 
        {>>{ usbdev_usb_tx_se0_o }}, {>>{ usbdev_usb_tx_use_d_se0_o }}, 
        {>>{ usbdev_usb_rx_enable_o }}, {>>{ usbdev_usb_ref_val_o }}, 
        {>>{ usbdev_usb_ref_pulse_o }}, {>>{ clk_main_i }}, {>>{ clk_io_i }}, 
        {>>{ clk_usb_i }}, {>>{ clk_aon_i }}, {>>{ clks_ast_o }}, 
        {>>{ rsts_ast_o }}, {>>{ scan_rst_ni }}, {>>{ scan_en_i }}, 
        {>>{ scanmode_i }} );
endmodule
`endif
